# Generated by Django 5.0.4 on 2024-05-12 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(6)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(6)),
        ),
    ]
